package com.github.fabiopelliccia.claudesessionsimportexport.core

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Test
import java.io.BufferedReader
import java.io.StringReader

class SessionTitleTest {

    private fun titleOf(vararg lines: String): String? =
        SessionTitle.of(BufferedReader(StringReader(lines.joinToString("\n"))))

    private fun user(content: String, meta: Boolean = false) =
        """{"type":"user","isMeta":$meta,"message":{"role":"user","content":"$content"}}"""

    @Test
    fun `the markup Claude Code writes before the first prompt is skipped`() {
        // The opening lines of real transcripts: a slash command, its caveat and output, a system
        // reminder, a tool result - and only then what the user actually asked.
        val title = titleOf(
            user("<command-message>design</command-message>\\n<command-name>/design</command-name>"),
            user("<local-command-caveat>Caveat: The messages below were generated by the user.</local-command-caveat>", meta = true),
            user("<command-name>/model</command-name>\\n<command-message>model</command-message>\\n<command-args>opus</command-args>"),
            user("<local-command-stdout>Set model to Opus</local-command-stdout>"),
            user("<system-reminder>\\nThis conversation is now continuing in the desktop app.\\n</system-reminder>"),
            """{"type":"user","message":{"role":"user","content":[{"type":"tool_result","tool_use_id":"t1","content":"ok"}]}}""",
            user("<ide_opened_file>The user opened Foo.kt</ide_opened_file>  Il plugin è sviluppato.\\n   Come lo provo?"),
            user("second prompt"),
        )
        assertEquals("Il plugin è sviluppato. Come lo provo?", title)
    }

    @Test
    fun `a custom title wins over a summary, and a summary over the first prompt`() {
        assertEquals(
            "Release checklist",
            titleOf(
                user("First prompt"),
                """{"type":"summary","summary":"Summary line","leafUuid":"x"}""",
                """{"type":"custom-title","customTitle":"Release checklist","sessionId":"s"}""",
            ),
        )
        assertEquals("Summary line", titleOf(user("First prompt"), """{"type":"summary","summary":"Summary line"}"""))
    }

    @Test
    fun `without a typed prompt the opening slash command names the session`() {
        assertEquals(
            "/review 42",
            titleOf(
                user("<command-name>/review</command-name>\\n<command-args>42</command-args>"),
                user("<local-command-stdout>done</local-command-stdout>"),
            ),
        )
    }

    @Test
    fun `the last recorded prompt is the fallback of a session with no user line`() {
        assertEquals(
            "Commit the working tree changes",
            titleOf(
                """{"type":"mode","mode":"normal"}""",
                """{"type":"last-prompt","lastPrompt":"Commit the working tree changes","sessionId":"s"}""",
            ),
        )
    }

    @Test
    fun `sidechain lines and generated lines are not prompts`() {
        assertEquals(
            "Real question",
            titleOf(
                """{"type":"user","isSidechain":true,"message":{"role":"user","content":"Subagent task"}}""",
                user("[Request interrupted by user]"),
                user("Real question"),
            ),
        )
    }

    @Test
    fun `a long prompt is cut and nothing at all gives no title`() {
        val long = "a".repeat(SessionTitle.MAX_LENGTH + 20)
        assertEquals("a".repeat(SessionTitle.MAX_LENGTH) + "…", titleOf(user(long)))
        assertNull(titleOf("""{"type":"mode","mode":"normal"}""", "not json"))
    }
}
